### ISSUE TITLE
WiFi adapter driver 8188eu

### ISSUE THREAD

**Issue by krios-fabteam** [FABtotum/fabui-colibri#10]
Driver for WiFi adapter 8188eu (newer dongle, have tiny button on the back) not loaded automatically.

**Comment by krios-fabteam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Beta Github Issues](https://trello.com/c/XDl81yUZ/131-beta-github-issues)

**Comment by krios-fabteam** [comment]
Should be fixed in the latest FABUI update.

**Comment by PaoloP74** [comment]
Wifi work on my FabTotum (hardware v.3).
I had to disable the ipv6 stack because they had priority on ipv4, but ipv6 in my network does not have internet connection.

**Comment by daniel-fabteam** [comment]
Did you disable the ipv6 stack on your network or on the fabtotum unit?

**Comment by PaoloP74** [comment]
I have disable IPV6 on my network.
