### ISSUE TITLE
Head nozzle override during print leads to NaN bug

### ISSUE THREAD

**Issue by mgcrea** [FABtotum/fabui-colibri#105]
Just tried to override the head nozzle height during print and it failed to properly update it, did set it to NaN (NotANumber) and the bed kept hitting on the nozzle. You should guard against sending the command if `isNan(number)`.

**Comment by daniel-fabteam** [comment]
Is the override value `NaN` there from the beginning?
Which browser/OS and language do you have?

**Comment by mgcrea** [comment]
Cannot reproduce it anymore with latest version (not sure if fixed by #104).
