### ISSUE TITLE
WiFi adapter driver 8192cu

### ISSUE THREAD

**Issue by krios-fabteam** [FABtotum/fabui-colibri#11]
Buggy driver for WiFi adapter 8192cu (older dongles. Don't have a tiny button on them).

It works after a reboot but when wifi network is changed it stops working.

**Comment by krios-fabteam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Beta Github Issues](https://trello.com/c/XDl81yUZ/131-beta-github-issues)

**Comment by krios-fabteam** [comment]
Fixed in the latest FABUI update.
Please confirm if it really was fixed.

**Comment by bilderbuchi** [comment]
I can at least confirm that the wireless (already working before) still works after the update. You propose to connect by cable, change wireless setings, and change them back I guess?

**Comment by bilderbuchi** [comment]
OK, I can confirm that the issue is fixed - you can dicsonnect/connect wireless without a reboot now.

**Comment by daniel-fabteam** [comment]
@bilderbuchi Great, thanks for the help.

**Comment by bilderbuchi** [comment]
you're welcome
