### ISSUE TITLE
setting z-probe for homing not taken into account before restart

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#112]
Setting made on the hardware tab for usage of probe during homing of z axis is at least only taken into account for nozzle height calibration after reboot. Please make users aware by means of a pop up giving them the ability to restart, but preferably make sure setting is active after clicking save button.

**Comment by daniel-fabteam** [comment]
Are you running the latest fabui version and fw?

**Comment by christopherwit** [comment]
My latest SD image was downloaded last Sunday and updated in fabui just
before posting this issue. Firmware is the most recent. I will reflash my
SD card and keep you posted.

Op 23 mrt. 2017 9:44 AM schreef "daniel-fabteam" <notifications@github.com>:

**Comment by christopherwit** [comment]
Fixed in latest firmware 0.99.20170323.1742
