### ISSUE TITLE
Can't Upload to project manager

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#113]
The smaller bar on the box with the file name and size completes and gives the checkmark but the progress bar on the top never fills, and when I refresh the page the file has not been added to the project.

**Comment by daniel-fabteam** [comment]
What language did you configure for the user interface?

**Comment by AndrewKillian** [comment]
English and I used both safari and google chrome on windows and MacOS I think it may have been an issue with the file name which had an apostrophe if that's the issue a message would be helpful for the future.

**Comment by daniel-fabteam** [comment]
Will be fixed in the next update.

Once you confirm it's fixed close this issue.
