### ISSUE TITLE
unit shuts down when 3d printing

### ISSUE THREAD

**Issue by mjb984** [FABtotum/fabui-colibri#117]
the unit turns off out of nowhere when printing. have attempted 3 different items and none has finished. the unit just turns off. no error or sound. this is not occurring with the laser head.

please advise

**Comment by daniel-fabteam** [comment]
When you say shuts down you mean the unit losses power?

**Comment by mjb984** [comment]
It completely powers off randomly.

**Comment by daniel-fabteam** [comment]
There are not features to power off the unit. Especially as RPi does not support that in hardware.

Please check that the power cable is not loosing the contact anywhere.

**Comment by daniel-fabteam** [comment]
Closing this issue as it is not software related.
