### ISSUE TITLE
After End of Print  Maintenance not accessible

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#124]
Fabui
    0.99.20170330.1726

After a print has finished, the menu-item 'Maintenance' (and 'Settings') are not accessible.
I had to leave the FabUI and reload it.

**Comment by krios-fabteam** [comment]
Which browser are you using?

**Comment by homahe** [comment]
I'm using Firefox 51.01 (64bit) on Linux (Debian).

I'll install the FireFox developer edition, so I can check what's going
on when I can't access the Maintenace-Option aftere the next print.


cu

**Comment by krios-fabteam** [comment]
Fix will be available with the next update.
Once you confirm it is fixed, please close this issue.
