### ISSUE TITLE
left sub menus not accessible after finishing assisted nozzle height calibration

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#125]
Assisted nozzle height calibration is now working correctly, but when wizard finishes I have to refresh without cache(ctrl+f5) FABUI to get access to all the left sub menus.
Similar to #124 but noticed after different action

**Comment by krios-fabteam** [comment]
Which browser are you using?

**Comment by christopherwit** [comment]
Firefox latest version for windows

Op 31 mrt. 2017 9:46 AM schreef "Krios Mane" <notifications@github.com>:

**Comment by christopherwit** [comment]
Fixed? Not possible to replicate in latest release.
