### ISSUE TITLE
After autobed leveling no heating of bed

### ISSUE THREAD

**Issue by casuda** [FABtotum/fabui-colibri#126]
When I start a print with auto bed leveling and the probing of the bed finished, the print stucks.
The bed does not heated and I have to restart the print again without auto leveling.

**Comment by krios-fabteam** [comment]
could you update your unit with the today's update and try it again? 
(ps: remember to reboot the unit after the update task is finished)

**Comment by casuda** [comment]
I can't upgrade the fablin it doesn't work...

**Comment by casuda** [comment]
on both FABs V1 and V2.... the update procedure starts and say finish, but after an reboot or shutdown and start the Fablin 1.0.0097.2-rc3 was shown.... to upgrade

**Comment by krios-fabteam** [comment]
Wich firmware in installed on your units?
Could you paste here "M503" output from "Maintenance>System Info" ?

**Comment by casuda** [comment]
On Core V2
Druckereinstellungen (Ausgabe M503)
Steps per unit
M92 X72.58 Y72.58 Z2133.33 E1524.00
Maximum feedrates (mm/s)
M203 X550.00 Y550.00 Z15.00 E12.00
Maximum Acceleration (mm/s2)
M201 X10000 Y10000 Z50 E100
Acceleration: S=acceleration, T=retract acceleration
M204 S4000.00 T100.00
Advanced variables
M205 S0.00 T0.00 B20000 X20.00 Z0.40 E1.00
Home offset (mm)
M206 X0.00 Y0.00 Z0.00
PID
M301 P20.00 I3.50 D30.00
Servo Endstop
R: 44 E: 147
Z Probe Length
-38.00
Installed head ID
2
Batch number
5
Baudrate
250000
FABlin version
1.0.0097.2-rc2

**Comment by krios-fabteam** [comment]
Let's split the 2 issues.
Could you also paste here the version of "FABUI" bundle?
If your unit was able to update fabui bundle with the installed firmware (1.0.0.0097.2-rc) you should start  a print with auto bed leveling. Can you confirm it? If yes you can close this issue and you can open a new one for the firmware update problem
