### ISSUE TITLE
numerous issues after update 0.99.20170407.1623, core v0.6.6

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#128]
After combined update FabUI 0.99.20170407.1623 and  core v0.6.6

-  Dashboard cannot connect to internet anymore
-  Maintenance -> Bed calibration -> returns 'Well this is embarrassing ... something went wrong'
-  Maintenance -> Head returns 
          Parse error: syntax error, unexpected ')', expecting ',' or ';' in /usr/share/fabui/application/views  
                            /head/install_js.php on line 31
          A PHP Error was encountered
          Severity: Parsing Error
          Message: syntax error, unexpected ')', expecting ',' or ';'
          Filename: head/install_js.php
          Line Number: 31
         Backtrace:
 -  Update returns:
         No internet connection found
         Check your connection and try again

(Connecting to the FabUI does work, so the static addresses of the FABtotum haven't been changed by the update. ) 
 -  Settings -> Network -> DNS  shows:
        Head:    (empty)
        Current: 8.8.8.8
        Tail:  8.8.8.8
                 8.8.4.4

 -  Loading filament:
         pushing about twice the length needed whereas the value of actual extruder steps didn't 
         change in 'step calibration'

- Maintenance -> Feeder -> Profiles:   nothing happens

Facit:  unusable

**Comment by krios-fabteam** [comment]
Fix will be available with the next update, we recommend you to download the new sd card that will be available today after 18.00 pm (GMT+1)
