### ISSUE TITLE
A couple of bugs..

### ISSUE THREAD

**Issue by ugo3d** [FABtotum/fabui-colibri#13]
After a calibration i tried to print but i got this error:
![bug_1](https://cloud.githubusercontent.com/assets/16561421/23305746/8c1ec782-faa0-11e6-863b-6b2041ea2d1e.JPG)
then i make a reboot and it stopped here:
![2bug](https://cloud.githubusercontent.com/assets/16561421/23305769/9f8ae8e6-faa0-11e6-84bc-f819c94318ba.JPG)
but with no rebooting.
making the sd again...
ciao

**Comment by AndrewKillian** [comment]
I had the same no reboot issue tried remaking the sd but no luck so far

**Comment by daniel-fabteam** [comment]
Could you create a separate issue for the two bugs you found. Is easier to track and handle.
In the new issues we will continue the discussion.

Thanks for the help.

**Comment by krios-fabteam** [comment]
The first issue is fixed in the latest FABUI update.
Please confirm if it really was fixed.

**Comment by AndrewKillian** [comment]
I never got the first issue just the restarting and I was on Colibri then

**Comment by krios-fabteam** [comment]
Fix ready in repository, will be available with the next update
