### ISSUE TITLE
Feeder on first startup

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#131]
When I try to print after I turn the printer on, the feeder sounds higher pitched and makes a shaking noise when it extrudes. The filament it extrudes also pumps out instead of a steady stream. After I reset the board the problem goes away and it prints as usual.

**Comment by infinity0n3** [comment]
If you can replicate this error again. Download the `system logs` plugin and attach the logs here.

**Comment by AndrewKillian** [comment]
[archive.tar.gz](https://github.com/FABtotum/fabui-colibri/files/916901/archive.tar.gz)
