### ISSUE TITLE
Raspicam not detected

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#139]
Currently the settings-raspicam page doesn't detect raspicam in non of the following browsers:
firefox, edge, IE11 and google chrome.

**Comment by krios-fabteam** [comment]
Hi @christopherwit , 
could you paste here M503 output (you can get it in Maintenance > System Info)

**Comment by christopherwit** [comment]
Hi guys in latest release 0.99.20170419.1714 I do get camera visuals when I use detect button in the no camera detect message.

**Comment by daniel-fabteam** [comment]
@christopherwit After using the `Detect` button, does the camera stay detected later?

**Comment by christopherwit** [comment]
I'm not sure after a restart, but within the same browser and session the
camera stays detected.
Maybe I can test a bit further this evening. I'll keep you updated.

2017-04-20 10:29 GMT+02:00 daniel-fabteam <notifications@github.com>:

**Comment by christopherwit** [comment]
Hi daniel, yes it still works when detect is selected even after a full power down and restart.
Which made it only an minor issue that it doesn't work right out of the box :)

**Comment by daniel-fabteam** [comment]
The detection is done during first boot so the issue should not be there on a fresh install and after full release.
