### ISSUE TITLE
Gcode lookup on jog page not working

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#140]
Gcode look up table renders with the following php error in firefox:

    GCode
    Description

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: jog/widget.php

Line Number: 261

Backtrace:

File: /usr/share/fabui/application/views/jog/widget.php
Line: 261
Function: _error_handler

File: /usr/share/fabui/application/controllers/Jog.php
Line: 41
Function: view

File: /usr/share/fabui/index.php
Line: 316
Function: require_once

**Comment by daniel-fabteam** [comment]
Go to `Update -> Firmware` and make sure the checkbox for the firmware update. Then click on `Update` button. This will download the firmware and it's gcode description again,

There was a typo in the gcode description file and is fixed now.
