### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by lahines100** [FABtotum/fabui-colibri#15]
After loading the software and receiving the steady blue light, I was unable to connect to the printer. I was using a cable connection. 
The original FABUI still works.

**Comment by daniel-fabteam** [comment]
@lahines100 which version of unit do you have? Is it a RPi1 or RPi3 base?

**Comment by lahines100** [comment]
I solved the issue today by reformatting the 8GB memory chip to 2GB and 6GB. When the new software was loaded into the 2GB section I could then log onto the FABtotum. It appears the size of the memory card does matter. Also, I upgraded to the new core a few weeks ago.
Thanks Daniel.

**Comment by daniel-fabteam** [comment]
@lahines100 Size should only matter in the sense that is has to be big enough which is 4GB.
Maybe the sdcard was formatted into unsupported filesystem.

Could you try to format the sdcard again fully (8GB no subpartitions) but make sure to select FAT32 filesystem.

**Comment by daniel-fabteam** [comment]
As the issue seems to be fixed I'll close it.
Make sure to checkout the new sdcard as we released today. The intention is to release a new sdcard image every day as long as there are open issues.
