### ISSUE TITLE
Not an issue, just a correction...

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#157]
In the JOG main-window there is 

XYZ Feedrate (mm/s²)

The normal nomenclature for a rate is    1 unit / 1 time-unit   or time-related unit,  e.g  [1/min] or [rpm]
or a speed unit as [km/h]

The unit [mm/s²]  stands for an acceleration

Scnd:

If you have chosen Maintenance -> Bed calibration the text for bed calibration

'This wizard will help you level the bed by setting the calibration screws of the bed to the correct height.
  Use the provided hex key and make sure the screws are almost halfway in'

is shown.  If now you switch over to 'Nozzle calibration' without having done the bed-calibration, the same is shown again.

The same mechanism of not changing to the text appropriate is true for other topics in the menu.

**Comment by daniel-fabteam** [comment]
The first typo is fixed.
The second behavior is not replicable. 

When you got stuck with the same text everywhere. How did the url in the address bar look like?
