### ISSUE TITLE
Laser Head feature request?

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#165]
Hey,
why not activating the laser-head add-on automatically, when you add the laser-head via the menu?
(No need to deactivate it, when the head is removed, or is it?)
This might avoid some frustration..

Besides, when one does a home x y, hits the centre button then and starts a laser-write, he'll get an alert window with a lengthy .php complain...

**Comment by daniel-fabteam** [comment]
Could you paste the lengthy php complain here?

**Comment by krios-fabteam** [comment]
Feature available from fabui version 1.0.5
