### ISSUE TITLE
no printhead in make print

### ISSUE THREAD

**Issue by nicolasvandenplas** [FABtotum/fabui-colibri#166]
after installing colibri software and do first setup.
where all is going fine, (bed calibration, head installing , spool load , calibrating bed, )
in make I go to print and it do not see any printer head.
in software it say that the printer head is installed.

**Comment by krios-fabteam** [comment]
Hi, 
could you paste here a screenshot of what you see when you go in "_Make > Print_" ?
and could you also paste here "M503 Output" (you can find it by going to "_Maintenance > System Info_")

**Comment by nicolasvandenplas** [comment]
![2017-05-04 17_42_22-no print head - windows photo viewer](https://cloud.githubusercontent.com/assets/28382302/25712169/32d620c6-30f1-11e7-868a-e75f84fb7354.png)
![2017-05-04 17_44_13-first setup - windows photo viewer](https://cloud.githubusercontent.com/assets/28382302/25712219/59f496ba-30f1-11e7-86ce-3ebba85976dd.png)
![2017-05-04 17_44_56-system info - windows photo viewer](https://cloud.githubusercontent.com/assets/28382302/25712256/7431e370-30f1-11e7-84a8-2830e5f8a4c1.png)

**Comment by nicolasvandenplas** [comment]
hoop this helps.
greetings Nicolas

**Comment by krios-fabteam** [comment]
Your unit is running with an old firmware version, please update it (go to "_Updates_" page or "_Maintenace > Firmware_")
Could you also go to "_Jog_" panel and send the command "M745" and paste here the response?

**Comment by nicolasvandenplas** [comment]
![2017-05-04 19_56_42-jog](https://cloud.githubusercontent.com/assets/28382302/25718155/5082397a-3105-11e7-8214-080e4a48cea4.png)

**Comment by nicolasvandenplas** [comment]
this do not do anything.
and the firmware is also not downloading .
after download it still say that the old firmware is on

**Comment by nicolasvandenplas** [comment]
![2017-05-04 20_13_27-firmware](https://cloud.githubusercontent.com/assets/28382302/25718439/5d17d842-3106-11e7-9b71-c7b1f73fa027.png)
![2017-05-04 20_14_24-firmware](https://cloud.githubusercontent.com/assets/28382302/25718441/60463cde-3106-11e7-97e7-a365199dfff7.png)

**Comment by nicolasvandenplas** [comment]
can I find a tutorial on how to do it.
I think I do something bad
and a link to the download page to find it like that?
greetings Nicolas

**Comment by daniel-fabteam** [comment]
Could you?
1) install the `System Logs` plugin 
2) try to install latest fw from `Maintenance > Firmware`
3) attache the logs here

You can find the System Logs plugin under Plugins > Online. Click on Install and then on Activate.
You will get a new menu item. Click on it and then on download. It will take some time to compact all the logs.

**Comment by nicolasvandenplas** [comment]
![2017-05-05 14_05_27-updates](https://cloud.githubusercontent.com/assets/28382302/25744909/948865a8-319c-11e7-8afe-d4cc4fc79b67.png)

**Comment by nicolasvandenplas** [comment]
FW not able to download
system login installed

**Comment by nicolasvandenplas** [comment]
![2017-05-05 14_14_18-plugins](https://cloud.githubusercontent.com/assets/28382302/25745015/3831c3f2-319d-11e7-8b69-45ca37fa6f16.png)

**Comment by nicolasvandenplas** [comment]
[archive.tar.gz](https://github.com/FABtotum/fabui-colibri/files/979279/archive.tar.gz)

**Comment by nicolasvandenplas** [comment]
can you send me a link  with the zip file that I can install ?

FABui 0.987 software
and to firmware 1.0.0098

it is a week that I can't work with my printer, maybe I put back fabui software

**Comment by nicolasvandenplas** [comment]
so that I can put it on my pc and try to upload it from there.

thanks Nicolas

**Comment by krios-fabteam** [comment]
Here  you can find the links:
[http://www.fabtotum.com/restore-corrupted-sd-card/](http://www.fabtotum.com/restore-corrupted-sd-card/)

**Comment by nicolasvandenplas** [comment]
hello
I did install the FABui soft and the printer is working ok.
I still have the old firmware running , is there a way to update it ?

I also have still the SD card whit the Colibri software on it, hoop that there is a way to make it work.

I see that in the colibri software the printer head is named (printer head light )
and in the FAbui software it is named (printer head V2)

hoop this helps to in proof the software

greetings Nicolas
