### ISSUE TITLE
Probe angle calibration values gets reset at every power on

### ISSUE THREAD

**Issue by LeiEng** [FABtotum/fabui-colibri#169]
On my FABtotum I have to change the probe calibration values to 140 (open position) and 36 (closed position) to get the probe angle correctly set both vertical and horisontal. I do this in the "MAINTENANCE -> Probe calibration -> Angle calibration" menu.

Unfortunately these values are reset to defautl values (127 and 25) every time I power off /power on my FABtotum. So I have to enter them after every power on.

**Comment by krios-fabteam** [comment]
Fix will be available with the new updates
