### ISSUE TITLE
Can't print curves

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#17]
When printing on curves the printer extruded way too much and made strange straining sounds, just leaving huge blobs, but straight lines printed properly.

**Comment by daniel-fabteam** [comment]
Could you attach the gcode file you were printing?

**Comment by AndrewKillian** [comment]
It was just two of the samples, the water jug one I think it was called and the logo key chain and I'm pretty sure the 3.
I reformatted the sd card after this and it worked fine.

**Comment by krios-fabteam** [comment]
Great,
so we can close the issue

**Comment by AndrewKillian** [comment]
Yep I'll post again if it comes back up.
