### ISSUE TITLE
fablin 1.1.0 does not get installed by update

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#170]
Hi Guys,

Finally I had some time left to get on with my fabtotum and noticed all your updates. Congratulations on the release of the first major version of Colibri. 

Unfortunately I'm stuck at fablin 1.0.0098 as firmware version 1.1.0 does not get installed by the automatic updater.

**Comment by christopherwit** [comment]
Sorry mo clue what went wrong, but after 8 attempts the system somehow made it till the end. Currently running fablin 1.1.0 with great success.

**Comment by daniel-fabteam** [comment]
Hi Christoper,

The firmware can always be installed from `Maintenance > Firmware` in case something goes wrong with update.

Is just a tip. Always report an issue when something is not working as it should.
