### ISSUE TITLE
Bed leveling problems

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#172]
when calibrating a second time the probe will come out and the head will move to each of the four positions but the bed will never actually move up to probe and the calibration never finishes

**Comment by daniel-fabteam** [comment]
Have you updated the firmware to 1.1.0?

**Comment by AndrewKillian** [comment]
yes

**Comment by LeiEng** [comment]
I can confirm that I have the exact same problem. And I have no updates pending (the firmware is 1.1.0).

**Comment by krios-fabteam** [comment]
The fix will be available with the new updates,  there will be also a firmware update

**Comment by AndrewKillian** [comment]
I have updated the software and now the procedure does not begin at all it just beeps and says well done for all.

**Comment by Mnemo80** [comment]
Turn on the probe test before the print in the setting section.  Do the bed leveling and then turn it off the option again if you want.
