### ISSUE TITLE
Fab-UI Colibrì don't boot

### ISSUE THREAD

**Issue by PaoloP74** [FABtotum/fabui-colibri#179]
Latest version of Fab-UI Colibri don't boot.

**Comment by krios-fabteam** [comment]
Hi @PaoloP74, 
could you confirm you flashed a new sd card by following the [installation guide](https://github.com/FABtotum/fabui-colibri/wiki/Installation), for the official release a simple update from "Update" page is not enough

**Comment by PaoloP74** [comment]
Yes. I deleted all SD partitions with "MiniTool Partition wizard" and created a single FAT32 partition. I copied the contents of the sdcard_latest.zip file and inserted the SD into the FabTotum.
The legs flash yellow and do not become blue.
With earlier versions I did not have this problem. I will try with a different SD.

**Comment by krios-fabteam** [comment]
Did you also set "BOOT" as label for the FAT32 partition?

**Comment by PaoloP74** [comment]
All ok. SD is broken. The other SD work.
