### ISSUE TITLE
probe angle range

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#181]
What has changed in probe extend and retract angles, and why? Previously it was working OK.

Now my issue, clearly the extend angle value is limited to 165. You cant set any value above 165.
Previously my probe was perfectly vertical with a value of 127, but now it needs a value of more than 170 to make it deploy 90degrees.
With 165 the probe gets close to vertical but needs a few degrees still. I would make a well estimated guess a deploying value of 180 would allow me to get it completely vertical.

Please fix this issue once more and promise you wont try to improve things in future when it is already working.

**Comment by infinity0n3** [comment]
Which part did you update? FabUI bundle or the firmware?

**Comment by daniel-fabteam** [comment]
Which part did you update? FabUI bundle or the firmware?

**Comment by christopherwit** [comment]
Everything, fabui, Fablin all to most recent version.

Op 15 jun. 2017 10:11 AM schreef "Daniel Kesler" <notifications@github.com>:

Which part did you update? FabUI bundle or the firmware?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FABtotum/fabui-colibri/issues/181#issuecomment-308661208>,
or mute the thread

**Comment by krios-fabteam** [comment]
This looks like more a related hardware issue. We didn't change anything about probe's angles,  if is needed to set angles bigger than 165 it means that the probe is not mounted as it should.  
Please contact support team by opening a [ticket](http://www.fabtotum.com/tickets) they will help you fix this issue
