### ISSUE TITLE
"Build plate needs to be flipped to the printing side"

### ISSUE THREAD

**Issue by brettdaniels** [FABtotum/fabui-colibri#187]
Replaced my blue tape this morning and went to level the bed... got this error message:

"Build plate needs to be flipped to the printing side." 

It is on the printing side... wth is causing it to think otherwise? It won't let me continue to level the bed... help please

**Comment by dmnc-net** [comment]
@brettdaniels How did you solve this problem. What this error even means?

**Comment by dmnc-net** [comment]
@brettdaniels How did you solve this problem? What this error even means? Bed has to be placed with the glass on the top? Yes, it is, I can even level the bed in the Jog page but I can't calibrate it.

@simone-fabteam

**Comment by krios-fabteam** [comment]
hi @dmnc-net, 
please make sure bed is correctly connected to the togo pins
could you paste here `M744` response? (Please use MDI in Jog panel)
If the bed is correctly connected you should get `TRIGGERED` otherwise `OPEN`
Could you also paste here `M503` output?
We look forward to your feedback.

**Comment by dmnc-net** [comment]
Hi, thanks for your reply. I found the issue, calibration screws was too high so there was s problem with pins. Now calibration works. Thanks
