### ISSUE TITLE
Photogrammetry scan does not finish

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#189]
When doing a photogrammetry scan, the process will never finish leaving the last picture untaken. When in post processing, this causes some issues in finishing the model. The project cannot be aborted at the end either it must be emergency stopped because when aborted it says there is a timeout error.

**Comment by krios-fabteam** [comment]
hi @AndrewKillian, 
which head was installed during the scan?
which firmware version is running on your unit?

**Comment by krios-fabteam** [comment]
Fix will be available with the next fabui bundle update (1.0.4)
