### ISSUE TITLE
Skip instead of Next in the 1st setup

### ISSUE THREAD

**Issue by dmnc-net** [FABtotum/fabui-colibri#194]
There is a label **Skip** instead of **Next** after filling the name, s/n and the color...

![setup](https://user-images.githubusercontent.com/2069874/27910353-2476d3be-6255-11e7-90c5-821b69db47a0.png)

**Comment by krios-fabteam** [comment]
Hi @dmnc-net, 
actually is right, this step could be skipped

**Comment by dmnc-net** [comment]
Hi,
but how to save it, it is only possible to skip it ...
