### ISSUE TITLE
WiFi passphrase can't contain some characters

### ISSUE THREAD

**Issue by dr4Ke** [FABtotum/fabui-colibri#202]
I'm trying to use WiFi with the given dongle. I didn't try it in months, but it was working a year ago or so.
Now I can't set correctly my passphrase (didn't change in the meantime). When I go to the `/var/lib/connman/user_wifi.config`, I see that my passphrase was changed. It lacks `'` and `*` characters.

When I correct the passphrase in this file, the connection is working well.

I think the UI code checks this field for SQL query attacks, but it shouldn't.

**Comment by krios-fabteam** [comment]
Thanks @dr4Ke,
we will look into it and will let you know as soon as possible

**Comment by krios-fabteam** [comment]
Fix will be available in the next update
