### ISSUE TITLE
First setup button doesn't work

### ISSUE THREAD

**Issue by bilderbuchi** [FABtotum/fabui-colibri#21]
When I go to dashboard-maintenance-first setup, I get "Error requesting maintenance/first-setup: 500 Internal Server Error".
I just freshly installed Colibri, all other menu items so far are accessible, I was affected by #11 afaict, but now after a reboot I am on a fully updated machine.
```
OS 	Linux fabtotum 4.4.38-v6 #1 Thu Feb 23 14:02:32 CET 2017 armv6l GNU/Linux
Firmware 	v1.0.0097.1
FabUI 	v0.9
Hardware 	v1
Installed Head 	hybrid_head
```

**Comment by LuxAetern** [comment]
+1 
have the same error with the exact same config

**Comment by krios-fabteam** [comment]
Hi guys, 
we'll add again the feature before the official release

**Comment by daniel-fabteam** [comment]
First-setup has been returned with a new look.

**Comment by bilderbuchi** [comment]
thanks! I hope I'll try it out soon!
