### ISSUE TITLE
Problem installing firmware

### ISSUE THREAD

**Issue by Morellid97** [FABtotum/fabui-colibri#220]
Hi everyone, i recently bought a Fabtotum core, and after 4 months int started having problems, (I was unable to locate it's IP address) so I decided to flash the firmware on the SD card. After completing the steps on the fabtotum guide lines site I am stuck on compiling the marling.io file. It seems like it cannot find some .h files so it wont compile. After reputting the old files on the SD card it wont even reeboot now. Anyone can help me on that?

**Comment by PaoloP74** [comment]
Hi, it is not necessary to compile any files.
You simply have to copy the files to a FAT32 formatted SD and insert it into the Raspberry SD slot.
You can find the latest release of the FabUI here: https://github.com/FABtotum/fabui-colibri/releases/tag/1.1.6
While the instructions for the SD can be found here: https://github.com/FABtotum/fabui-colibri/wiki/SD-card-formatting
The FabTotum IP address is 169.254.1.2

**Comment by rayyash** [comment]
Just download and extract the fab ui files from the zipped folder then copy
them directly on the SD. No other steps are needed.

**Comment by Morellid97** [comment]
Thanks guys, it works now!
