### ISSUE TITLE
[minor] My name is "undefined"

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#27]
When I have a message addressed to me, the OS call me "undefined"...

**Comment by daniel-fabteam** [comment]
Could you specify which message it is?

There was a bug with on the shutdown popup but is fixed in the latest sdcard image / fabui update. 
See #22

**Comment by florentmaye** [comment]
Ok I think it was in the first version: I can't do any update due to my restart issue ^^.
I will tell you when I will reflash my SDcard ...
