### ISSUE TITLE
Printer restarted while in pause mode

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#35]
I was printing an object and I paused the process to do something manually. The printer correctly stopped and I proceed. But after a moment, the printer restarted without any reason ... (I was still operating on it)

**Comment by daniel-fabteam** [comment]
I cannot recall which unit version you have. You can check this in Maintenance -> System Info -> Hardware

I could be that while you were operating on it the front door was moved and "Door safety" reacted. The result is that all running processes are restarted.
Door safety can be disabled in Settings -> Hardware -> Safety
