### ISSUE TITLE
Laser Head Material Test Pattern

### ISSUE THREAD

**Issue by AndrewLShaw** [FABtotum/fabui-colibri#40]
When the Laser Material Test Pattern gcode file is loaded in the object manager the file is interpreted as a Print and not an engrave.

At first I assumed it may be because I loaded the file before I 'Installed' the laser head, but I have installed a fresh copy of Colibri and then installed the laser head, followed by the file upload. Same result.

**Comment by krios-fabteam** [comment]
Fixed in the latest FABUI update.
