### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by MrGonzi** [FABtotum/fabui-colibri#44]
ciao, 
vi allego un report che ho fatto qualche giorno fa, spero possa esservi utile.
saluti
Matteo conte
[Report test.docx](https://github.com/FABtotum/fabui-colibri/files/811779/Report.test.docx)

**Comment by krios-fabteam** [comment]
Ciao @MrGonzi  per il report.
Nel documento vi sono anomalie che risultano già essere sistemate, noi rilasciamo quotidianamente alle ore 18.00 un [sdcard aggiornata](http://update.fabtotum.com/colibri/armhf/images/sdcard_latest.zip), potrebbe scaricarla e riprovare di nuovo?
Le suggeriamo inoltre di dare un occhiata alla nostra guida [sulla formattazione della sdcard](https://github.com/FABtotum/fabui-colibri/wiki/SDCard-formatting) che va a risolvere il problema del non avvio della macchina dopo il primo spegnimento
