### ISSUE TITLE
Make menu has no LASER item in the list

### ISSUE THREAD

**Issue by BramElderman** [FABtotum/fabui-colibri#46]
I see people discussing the laser engraving however i don't have the laser option available in the menu,... is that because i have the RPi 1?? the old software has it available and i have done laser engraving with that... in the Colibri release it is nowhere to be seen 

i only have **print mill scan and history** in the make menu

<img width="1792" alt="schermafbeelding 2017-03-01 om 22 47 08" src="https://cloud.githubusercontent.com/assets/26010527/23483176/275de374-fed2-11e6-9eb1-75ed65235a91.png">

Maintenance System info also displays weird data,.. for the record i removed the laser head and reinstalled the hybrid head.

<img width="1792" alt="schermafbeelding 2017-03-01 om 22 50 25" src="https://cloud.githubusercontent.com/assets/26010527/23483252/798f6578-fed2-11e6-86ae-646fa790f5df.png">

**Comment by daniel-fabteam** [comment]
The laser menu item is disabled for now as it's still not fully ported to fabui-colibri. It will be available as a plugin which will serve also as an advanced example of how to make plugins in the new framework.

For the System Info issue. I had this few days ago but was resolved. If after refreshing the page it's still there open an issue so we can track it. That way if someone else has the same problem they can join the discussion.

**Comment by daniel-fabteam** [comment]
The latest update is released. Laser menu item is removed as well as all the logic behind it from main fabui.

However now we have a plugin to add laser functionality for people who need it.
Check it out and report any issues you find.
Is not completed yet but should allow you have some fun with the laser.

`Note: the upper folder icon in jog view is "Restore XY", the lower folder icon is "Restore Z". If you home XYZ first, when you press "Zero" the position will be store and can be restore next time you do some laser engraving`
