### ISSUE TITLE
Emergency buttons take its time

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#48]
I wanted to stop my height calibration when the plate was at the bottom (it's a trick I wanted to try to have it down, since I can't jog, I'm often stucked with the plate at maximal heigth, not really convinient ^^), so I pressed the emergency button (the one on calibration popup), but the printer took time to end the calibration before stopping ...

**Comment by krios-fabteam** [comment]
ixed in the latest FABUI update.
