### ISSUE TITLE
live print console fail

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#49]
When I send a command during a print to change the bed temperature, it happens that it isn't taken into account: I have the validation popup confirmation, but when I come later, the temperature in the monitoring curve is still the first one (real as target).Then I do the operation again and the second time the change is taken into account.

**Comment by daniel-fabteam** [comment]
Try the latest update. With this one you have to make a new sdcard.

It includes new nozzle calibration procedure and some fixes regarding print control.
