### ISSUE TITLE
False "Bed not installed" in jog view

### ISSUE THREAD

**Issue by daniel-fabteam** [FABtotum/fabui-colibri#51]
"Bed not installed" is shown in jog view even if the bed is in place and showing the correct temperature.
As mentioned by @homahe in #45

**Comment by sickforska** [comment]
I'm having this same issue. Jog shows "bed not installed", but I can set and monitor the temperature in the temp dropdown from the header, and the controls when a print starts.

**Comment by krios-fabteam** [comment]
ixed in the latest FABUI update.
