### ISSUE TITLE
notification popup

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#52]
Not sure if it's a bug. In the notification popup, when clicking on a task, it doesn't do anything (I was expecting it to show me the task view)

**Comment by marco-fabteam** [comment]
@florentmaye
yes it's supposed to show the task. Can you please specify wich task and if it's actually running (as in physically working or just a ghost task)? Thanks.

**Comment by florentmaye** [comment]
It is a print which was running

**Comment by daniel-fabteam** [comment]
The fix will be available in the next update.
