### ISSUE TITLE
hardware menu doesn't work when printing

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#53]
I wanted to check with the raspicam my print be none of the menu in hardware category worked ...

**Comment by krios-fabteam** [comment]
Hi @florentmaye, 
this is not an error but is a desidered behavior to avoid any interferance with the running tasks

**Comment by florentmaye** [comment]
Ok then the raspberry camera lose its main purpose which is to check the print remotly, don't you think ?
