### ISSUE TITLE
Shutdown using power icon

### ISSUE THREAD

**Issue by lahines100** [FABtotum/fabui-colibri#55]
Os     Linux fabtotum 4.4.38-v7 #1 SMP Fri Feb 24 12:09:42 CET 2017 armv7l GNU/Linux
Fabui     0.99.20170303.1728
Firmware     1.0.0097.1 - Build date: Jan 27 2017 17:29:17 - Author: FABteam 
Hardware     5
Installed head     Printing Head V2
After shutdown using the power icon the software is corrupted and needs to be reloaded. When turned on the yellow light flashes continuously and never turns blue. Software is in an 8GB FAT32 boot partition

**Comment by lahines100** [comment]
Works after ensuring no space before first partition on sd card. Seemed to start up without login however.

**Comment by marco-fabteam** [comment]
thanks, closed.
