### ISSUE TITLE
[improvement] possibility to disable a network interface

### ISSUE THREAD

**Issue by dr4Ke** [FABtotum/fabui-colibri#56]
I think it would be better if we had the possibility to just disable the ethernet or wifi interface. You could add a `Disable` choice in the interface together with `Static` and `Automatic (DHCP)`. In this case, the sane default for WiFi would be `Disable`.

**Comment by daniel-fabteam** [comment]
What would be the benefit of doing so?
By default ethernet and wifi are configured to static values without gateway. They don't take any significant time to setup during boot in that state.

**Comment by dr4Ke** [comment]
I guess it's just more satisfying. Plus, I wonder what would happen if one is using an ethernet network in the same range than the predefined WiFi static address.
Well, I tried this, and… it's working fine.

**Comment by BramElderman** [comment]
in a sense you already have that, if you don't insert the wifi stick the wifi tab is not available,.. it is ethernet only and works fine for me,.. only if you use both it might become confusing

**Comment by christopherwit** [comment]
In my opinion a button to disable wifi is a nice to have.

It does get a bit confusing when you run from a pi3 which has the wifi enabled by default, and both interfaces get utilised at the same time. Especially when fabui reports no internet connection but is connected to your network.

**Comment by daniel-fabteam** [comment]
Disable option for wireless interface is available in the latest update.
