### ISSUE TITLE
Icons in input fields misaligned in settings menu of installation

### ISSUE THREAD

**Issue by seppestas** [FABtotum/fabui-colibri#63]
The icons in the inputs fields of the settings menu shown during installation are misaligned with the input text, causing the icons to apear on top of the text:
<img width="505" alt="screen shot 2017-03-04 at 17 47 01" src="https://cloud.githubusercontent.com/assets/1408377/23580499/604045be-0103-11e7-95eb-ce8c0856671a.png">

## Environment
Chrome Version 56.0.2924.87 (64-bit)
OSX Version 10.12.3
fabui-colibri v20170225

**Comment by krios-fabteam** [comment]
Issue fixed with the latest FABUI update

**Comment by seppestas** [comment]
👍 can it already be tested?

**Comment by krios-fabteam** [comment]
Yes, just updating the new FABUI bundle or [downloading the latest sd card](http://update.fabtotum.com/colibri/armhf/images/sdcard_latest.zip)
