### ISSUE TITLE
Links to subsections on SD card formatting wiki page are incorrect

### ISSUE THREAD

**Issue by seppestas** [FABtotum/fabui-colibri#64]
The links to the "Windows", "Mac" and "Linux" subsections link to the non-existing https://github.com/FABtotum/fabui-colibri/wiki/SDCard-formatting page instead of the https://github.com/FABtotum/fabui-colibri/wiki/SD-card-formatting page, causing the links to be redirected to https://github.com/FABtotum/fabui-colibri/wiki.

**Comment by daniel-fabteam** [comment]
Thank you. Fixed.

**Comment by seppestas** [comment]
Hey @daniel-fabteam, I also found a typo on https://github.com/FABtotum/fabui-colibri/wiki/Installation:

"Wait for the leds to became blue" in the last point should be "Wait for the leds to become blue" or "Wait for the leds to turn blue".

Not really worth an extra issue though imo :)

**Comment by daniel-fabteam** [comment]
Also fixed. :)
