### ISSUE TITLE
Recovery activated at boot time

### ISSUE THREAD

**Issue by florentmaye** [FABtotum/fabui-colibri#65]
Half the time I boot my Fabtotum, I land on the recovery screen. I can then recove rcorrectly. I haven't identified any pattern leading to this situation. ( I had the impression that no ethernet cable plugged leads to that but in fact it seems it isn't the case)

**Comment by daniel-fabteam** [comment]
Have you tried just to do **boot** instead of recovery?

You can land at the recovery page in one of three cases
1) Filesystem has been corrupted in such a way that automatic fixes cannot help
2) The head is removed or does not have a good contact
3) Both Y endstops have been pressed

**Comment by florentmaye** [comment]
No never tried. I will next time.
I don't think I'm in #2 or #3 of these cases ...


Le 6 mars 2017 9:56 PM, "daniel-fabteam" <notifications@github.com> a
écrit :

Have you tried just to do *boot* instead of recovery?

You can land at the recovery page in one of three cases

   1. Filesystem has been corrupted in such a way that automatic fixes
   cannot help
   2. The head is removed or does not have a good contact
   3. Both Y endstops have been pressed

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FABtotum/fabui-colibri/issues/65#issuecomment-284529646>,
or mute the thread

**Comment by daniel-fabteam** [comment]
Has this issue been resolved with the latest sdcard image and fw version?
