### ISSUE TITLE
Dead on restart right after fresh install

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#68]
Just started the fabtotum successfully with fresh download of Colibri OS. Went trough setup and everything seems ok until I do a first reboot.
Something that might be relevant, I'm running my Fabtotum on a Pi3

Final error line posted during boot is at 11,5sec reading:
----{ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007e00

Let me know if you need additional data and how I can obtain this info for you.

**Comment by krios-fabteam** [comment]
Hi, 
with which operating system did you formatted the sd card? Did you follow our [SD card formatting](https://github.com/FABtotum/fabui-colibri/wiki/SD-card-formatting) guide? If not could you please try to format the SD card by following it?

Take a look also at the close issue  #20

**Comment by christopherwit** [comment]
Hi, fair chance it had something to do with the formatting as pointed out
in closed thread #20 <https://github.com/FABtotum/fabui-colibri/issues/20>
I'll give it a look and let you know about my progress.

Op 9 mrt. 2017 9:56 AM schreef "Krios Mane" <notifications@github.com>:

Hi,
with which operating system did you formatted the sd card? Did you follow
our SD card formatting
<https://github.com/FABtotum/fabui-colibri/wiki/SD-card-formatting> guide?
If not could you please try to format the SD card by following it?

Take a look also at the close issue #20
<https://github.com/FABtotum/fabui-colibri/issues/20>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FABtotum/fabui-colibri/issues/68#issuecomment-285292517>,
or mute the thread

**Comment by christopherwit** [comment]
Hi Following the SD card formatting wizard did the trick. Currently happily restarting :)
Thanks and sorry for not searching around before posting an new issue. Maybe update the install instructions on [this page](http://www.fabtotum.com/fabui-colibri-world-first-os-3dprinting/) as well (as this is where I started).

**Comment by krios-fabteam** [comment]
Don't worry @christopherwit , thanks for your contribution
Let's close the issue :)
