### ISSUE TITLE
404 error Nozzle/getLength on nozzle fine calibration

### ISSUE THREAD

**Issue by dr4Ke** [FABtotum/fabui-colibri#70]
Last update (0.99.20170309.1754), when accessing the Maintenance - Nozzle - Height calibration, Fine calibration: a popup shows, stating "Please wait..." and nothing more…

In the log file: there is this error: 404 Page Not Found: Nozzle/getLength

Do I lack a file?

**Comment by daniel-fabteam** [comment]
The issue will be fixed in the next update. Also make sure to make a new sdcard if you haven't. The new calibration procedure changed some internal files that are not changed during updates (for now).
Also update the firmware to latest rcX version that is only available in fabui-colibri.

**Comment by dr4Ke** [comment]
I can confirm that it's working with the last update.
