### ISSUE TITLE
Z step in Jog panel is actually in cm, not mm

### ISSUE THREAD

**Issue by dr4Ke** [FABtotum/fabui-colibri#72]
The title says it all. The value entered is multiplied by 10 in the sent command. Example:

- 5 entered in "Z Step (mm)" field
- command sent: `G0 Z+50.00 F1000.00`
- bed going down 5 cm

**Comment by daniel-fabteam** [comment]
There is a multiplier button saying now much the step value is modified.
It **x10** at when loaded. If you press it, it will switch to **x1** and **x0.1**

**Comment by dr4Ke** [comment]
Oh. OK. I didn't see it, or I didn't understand what it was doing. Sorry for the noise.
