### ISSUE TITLE
tooltip for Z height incorrect

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#75]
Tooltip for z height increments has the following text, while default value is set at 0.5:
Do not set a value lower than 1(actual text might be slightly different as I translated from Dutch)

**Comment by daniel-fabteam** [comment]
Could you specify in which view the tooltip is incorrect? Also I see you wrote "the following text" but don't see the text you are referring to.

Did you start working on Dutch translation?

**Comment by christopherwit** [comment]
Sorry for the confusion. Hopefully below is more clear. 
Tooltip for z height increments on the jog page has the following text:
"Do not set a value lower than 1" (actual text might be slightly different as I translated from Dutch)
while default value is set at 0.5

Actually looking more into it, I'm surprised I do get a tooltip on that setting. I have English selected, and I didn't start translating:) Maybe in the future I will.
In addition I don't get tooltips on other input boxes, and as far as my testing did go it only appears in Firefox....

**Comment by daniel-fabteam** [comment]
Is fixed in the latest update.
Note: It's required to make a new sdcard for the new update otherwise the feeder settings will not work properly.
