### ISSUE TITLE
can find 169.254.1.2 on the network, but cannot connect.

### ISSUE THREAD

**Issue by mpetr552** [FABtotum/fabui-colibri#83]
Hi, I am able to connect to the FABUI colibri via ethernet, when I plug the printer directly into my computer. However when I attempt to connect to the printer over the network, I am not able to connect. I am able to see that the host is up by running nmap, but still cannot connect. This may be a trivial issue, but would appreciate the assistance.
thanks!

**Comment by daniel-fabteam** [comment]
It would be better to ask this question on the forum as more users will see it and might offer help.
