### ISSUE TITLE
Scan Does not show progress

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#84]
When scanning only the elapsed time is shown there is no progress bar and the spot to tell you what slice it's on is empty
<img width="1027" alt="screen shot 2017-03-12 at 2 59 48 pm" src="https://cloud.githubusercontent.com/assets/16737537/23834905/90217d0c-0734-11e7-869a-9945004b4713.png">

**Comment by AndrewKillian** [comment]
the elapsed time was shown over ethernet on the computer I started it on but not over wireless on another one.

**Comment by krios-fabteam** [comment]
Should be fixed in the latest update
