### ISSUE TITLE
View Raspicam during prints

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#85]
I don't know if this is possible but a feature to allow you to view your print through the raspicam  to make sure the print hasn't failed would be very useful.

**Comment by christopherwit** [comment]
I don't agree, the raspicam is positioned in such a way, that the camera view is useless during the first 10cm of a print, as you won't see the print result. I do agree a camera view during print would be helpfull, but I guess it's a better solution to use a seperate camera for this purpose.

**Comment by AndrewKillian** [comment]
I see what you mean but
