### ISSUE TITLE
Abort Issues 

### ISSUE THREAD

**Issue by AndrewKillian** [FABtotum/fabui-colibri#90]
When aborting the print stops, however the bed never moves down and the message saying aborting print just stays there. I had to reset the board to get the message to go away.

**Comment by daniel-fabteam** [comment]
Did you abort the print in the heating phase or when the print started?

**Comment by AndrewKillian** [comment]
After the print started.

**Comment by daniel-fabteam** [comment]
Which version of fabtotum do you have? You can check this in the **Maintenance** / **System Info**

And does it still behave like that with the latest update? You need to make an new sdcard as we changed the back-end for feeder parameters handling.

**Comment by AndrewKillian** [comment]
This issue has been fixed with that latest update.
