### ISSUE TITLE
No print button in projectmanager on mobile device

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#92]
When viewing one of the objects in the projectmanager, the print button is rendered beyond my screen size and I'm unable to move the page around to get access to the print button. Even when I tap one of the printable items I do get the item page, but there is no action/print button as well.

My device is a rather small Sony xperia Z1 compact. 

Please find my screencapture attached below:
![screenshot_2017-03-14-22-07-18](https://cloud.githubusercontent.com/assets/14850081/23922670/8fd6b12a-0903-11e7-8146-cf66b0b01eff.png)

**Comment by daniel-fabteam** [comment]
Try to rotate your device to see more of the table.

**Comment by christopherwit** [comment]
Haha thanks for that bright suggestion :)
Just a small thing left: the pull-down menu renders (even with screen in landscape) of my screen:
![screenshot_2017-03-15-11-11-17](https://cloud.githubusercontent.com/assets/14850081/23943654/73a21ef0-0970-11e7-8844-c5b4e86f5727.png)

**Comment by krios-fabteam** [comment]
the fix will be available with the next update
