### ISSUE TITLE
Is there a way to completely dissable Z probe?

### ISSUE THREAD

**Issue by RobertsVancovics** [FABtotum/fabui-colibri#95]
In the setting I have ticked the option Homing> Use Z probe during homing>disabled.
The problem is that both, during nozzle height callibration and simple homing before prints the Z probe is being used. I broke my Z probe some time ago, so I cant use it. I have a custom printing head installed.

**Comment by daniel-fabteam** [comment]
Will be fixed in the next update.
You can also get a replacement probe from the [shop](https://store.fabtotum.com/eu/products/3d-printer-accessories/probe.html).
