### ISSUE TITLE
printing same part again 'heating nozzle heating bed' display permanent

### ISSUE THREAD

**Issue by homahe** [FABtotum/fabui-colibri#96]
Using the actual release of 17mar the display 'heating nozzle ...' that is displayed when the print starts, stays on, even when the temperatures are reached and the print has started. Reloading the browser-window (Firefox) doesn't change to the live-view, but changes the background-colour of the I/O fields to light-olive. Clicking 'jog' in the menu then, - may be another item of the menu too-, you can start the live view.

**Comment by krios-fabteam** [comment]
fixed with the latest update
