### ISSUE TITLE
php error on dashboard page

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#98]
Php error which popped up after reboot on the dashboard page instead of rendering twitter and instagram feed:

A PHP Error was encountered
Severity: Warning
Message: Invalid argument supplied for foreach()
Filename: helpers/layout_helper.php
Line Number: 297
Backtrace:
File: /usr/share/fabui/application/helpers/layout_helper.php
Line: 297
Function: _error_handler
File: /usr/share/fabui/application/controllers/Dashboard.php
Line: 165
Function: highlightInstagramPost
File: /usr/share/fabui/index.php
Line: 316
Function: require_once

**Comment by krios-fabteam** [comment]
Fixed with the latest update
