### ISSUE TITLE
installation in progress doesn't refresh page

### ISSUE THREAD

**Issue by christopherwit** [FABtotum/fabui-colibri#99]
After the installation wizard (with account credentials etc) has finished I get a flash screen which states: installation in progress, plaese wait (including typo), but it never refreshes the page.
When I refresh manually to the main ipnr everything is fine.

**Comment by daniel-fabteam** [comment]
Is this issue still present in the latest sdcard?

Also which browser are you using.

**Comment by christopherwit** [comment]
Fixed, but on the flash screen awhile is spelled as a while ;)

**Comment by daniel-fabteam** [comment]
It took a while to fix it but "awhile" is fixed now.
